#!/bin/sh

#############################
##          All            ##
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export SHELL=/bin/bash
export PULSE_SERVER=127.0.0.1

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r /root/.Xresources ] && xrdb /root/.Xresources

############################
##          XFCE          ##
startxfce4

############################
##          LXDE          ##
#startlxde

############################
##          LXQT          ##
#startlxqt

############################
##          KDE           ##
#startplasma-x11

############################
##          UKUI          ##
#ukui-session

############################
##        CINNAMON        ##
#cinnamon-session

############################
##          MATE          ##
#export XKL_XMODMAP_DISABLE=1
#mate-session

###########################
##         GNOME         ##
#export XKL_XMODMAP_DISABLE=1
#export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
#export XDG_MENU_PREFIX="gnome-flashback"
#gnome-session --session=gnome-flashback-metacity --disable-acceleration-check --debug &
#metacity &
#gnome-panel &
#budgie-panel &
#gnome-flashback &

##          END           ##
############################
