#!/bin/bash
#Soundfix
wget -q https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/kali -P ../usr/bin/

#Xstartupfix
rm kali-*/home/kali/.vnc/xstartup
wget -q https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/xstartup -P kali-*/home/kali/.vnc/

chmod +x ../usr/bin/kali
chmod +x kali-*/home/kali/.vnc/xstartup
rm nh
