#!/bin/bash
echo "Installing Packages,.."
echo ""
case `dpkg --print-architecture` in
                aarch64)
                        device="arm64" ;;
                arm*)
                        device="armhf" ;;
                i386)
                        device="i386" ;;
                x86_64)
                        device="amd64" ;;
                *)
                        echo "unknown architecture"; exit 1 ;;
esac
cp ~/kali-$device/home/kali/.bashrc ~/
rm ~/kali-$device/home/kali/.vnc/xstartup
wget https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/kali -P ../usr/bin/
wget https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/xstartup -P ~/kali-*/home/kali/.vnc/
wget https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/vnc-start -P ~/kali-$device/usr/local/bin/
wget https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/vncstart -P ~/kali-$device/usr/local/bin/
wget https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/vnc-stop -P ~/kali-$device/usr/local/bin/
wget https://raw.githubusercontent.com/wahasa/Ubuntu/main/Patch/passwd -P ~/kali-$device/home/kali/.vnc/
  chmod +x ../usr/bin/kali
  chmod +x ~/kali-$device/home/kali/.vnc/xstartup
  chmod +x ~/kali-$device/usr/local/bin/*
echo "
vnc-start
sleep 5
DISPLAY=:1 firefox &
sleep 10
pkill -f firefox
vnc-stop
sleep 2

wget -O $(find ~/kali-*/home/kali/.mozilla/firefox -name *.default-esr)/user.js https://raw.githubusercontent.com/wahasa/Ubuntu/main/Patch/user.js

exit" >> ~/kali-$device/home/kali/.bashrc ; bash kali
wget https://raw.githubusercontent.com/wahasa/Ubuntu/main/Patch/user.js -P ~/kali-*/home/kali/.mozilla/firefox/*.default-esr/
mv ~/.bashrc ~/kali-$device/home/kali/
rm ~/kali-$device/home/kali/.vnc/passwd
  clear
  echo ""
  echo "You can now start Kali with 'kali' script next time"
  echo ""
  echo "Start Vnc Server, run vnc-start"
  echo "Stop Vnc Server, run vnc-stop"
  echo ""
rm pkg-2
