#!/bin/bash
wget -q https://raw.githubusercontent.com/wahasa/Kali-Nethunter/main/Patch/kali -P ../usr/bin/
  chmod +x ../usr/bin/kali
  echo "You can now start Kali with 'kali' script next time"
rm pkg-1
