#!/bin/sh
export DISPLAY=:1
export PULSE_SERVER=127.0.0.1
rm -rf /run/dbus/dbus.pid
#dbus-launch $HOME/.vnc/xstartup

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export XKL_XMODMAP_DISABLE=1
#export XDG_CURRENT_DESKTOP="GNOME-Flashback:Unity"
export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
export XDG_MENU_PREFIX="gnome-flashback-"

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
#dbus-launch --exit-with-session gnome-session --debug &
#dbus-launch --exit-with-session gnome-session --builtin --session=gnome-flashback-metacity --disable-acceleration-check --debug &
#gnome-session --builtin --session=gnome-flashback-metacity --disable-acceleration-check --debug &
#gnome-settings-daemon &
xsetroot -solid grey

plank &
metacity &
gnome-panel &
gnome-flashback &
