#!/bin/sh

#############################
##          All            ##
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export SHELL=/bin/bash

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r /root/.Xresources ] && xrdb /root/.Xresources

############################
##          XFCE          ##
exec startxfce4

############################
##          LXDE          ##
#exec startlxde

############################
##          LXQT          ##
#exec startlxqt

############################
##          KDE           ##
#exec startplasma-x11

############################
##        CINNAMON        ##
#exec cinnamon-session

############################
##          MATE          ##
#xsetroot -solid grey
#x-window-manager &
#export XKL_XMODMAP_DISABLE=1
#exec mate-session

###########################
##         GNOME         ##
#xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
#export XKL_XMODMAP_DISABLE=1
#export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
#export XDG_MENU_PREFIX="gnome-flashback"
#gnome-session --session=gnome-flashback-metacity --disable-acceleration-check --debug &
#metacity &
#gnome-panel &
#budgie-panel &
#gnome-flashback &
#gnome-settings-daemon &

##          END           ##
############################
