#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
clear
printf "${blu}Welcome To Kali Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Debian"
printf "\n\n"
printf "${ylw}• Kali Nano (Cli)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Kali-Nano\n"
printf "${blu}Version ${red}: ${grn}2023.1\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64"
printf "\n\n"
printf "${ylw}• Kali Minimal (Cli + Pkg Kali)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Kali-Minimal\n"
printf "${blu}Version ${red}: ${grn}2023.1\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Kali Full (Cli + Pkg Kali + Desktop)"
printf "\n\n"
printf "${blu}Name    ${red}: ${grn}Kali-Full\n"
printf "${blu}Version ${red}: ${grn}2023.1\n"
printf "${blu}Status  ${red}: ${grn}Latest\n"
printf "${blu}Rootfs  ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Kali-Nano")
wget https://raw.githubusercontent.com/wahasa/nethunter/main/Install/kali-nano.sh ; chmod +x kali-nano.sh ; bash kali-nano.sh
        ;;
        "Kali-Minimal")
wget https://raw.githubusercontent.com/wahasa/nethunter/main/Install/kali-minimal.sh ; chmod +x kali-minimal.sh ; bash kali-minimal.sh
	;;
        "Kali-Full")
wget https://raw.githubusercontent.com/wahasa/nethunter/main/Install/kali-full.sh ; chmod +x kali-full.sh ; bash kali-full.sh
        ;;
        *)
	bash Install
        ;;
esac
